<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">

    <xsl:param name="base_url">https://www.imixs.org/doc</xsl:param>
    <xsl:output method="xml" indent="yes" encoding="UTF-8" />

    <xsl:template match="/">
        <urlset>
            <!-- static root level pages -->
            <url>
                <loc>https://www.imixs.org/index.html</loc>
                <priority>1.0</priority>
                <changefreq>monthly</changefreq>
            </url>
            <url>
                <loc>https://www.imixs.org/sub_community.html</loc>
                <priority>0.9</priority>
                <changefreq>monthly</changefreq>
            </url>
            <url>
                <loc>https://www.imixs.org/sub_jee.html</loc>
                <priority>0.9</priority>
                <changefreq>monthly</changefreq>
            </url>
            <url>
                <loc>https://www.imixs.org/sub_microservice.html</loc>
                <priority>0.9</priority>
                <changefreq>monthly</changefreq>
            </url>
            <url>
                <loc>https://www.imixs.org/sub_modeler.html</loc>
                <priority>0.9</priority>
                <changefreq>monthly</changefreq>
            </url>
            <url>
                <loc>https://www.imixs.org/sub_security.html</loc>
                <priority>0.9</priority>
                <changefreq>monthly</changefreq>
            </url>

            <!-- pages generated by maven site plugin - deduplicated -->
            <xsl:for-each
                select="//item[not(@target='_blank') 
                and @href 
                and not(contains(@href, 'apidocs'))
                and generate-id() = generate-id(key('hrefs', @href)[1])]">
                <xsl:apply-templates select="." />
            </xsl:for-each>
        </urlset>
    </xsl:template>

    <!-- Key for deduplication -->
    <xsl:key name="hrefs" match="item" use="@href" />

    <xsl:template match="item">
        <!-- normalize ./ paths -->
        <xsl:variable name="href">
            <xsl:choose>
                <xsl:when test="starts-with(@href, './')">
                    <xsl:value-of select="substring(@href, 3)" />
                </xsl:when>
                <xsl:otherwise>
                    <xsl:value-of select="@href" />
                </xsl:otherwise>
            </xsl:choose>
        </xsl:variable>
        <url>
            <loc>
                <xsl:value-of select="$base_url" />
                <xsl:if test="not(starts-with(@href, 'http'))">
                    <xsl:text>/</xsl:text>
                </xsl:if>
                <xsl:value-of select="$href" />
            </loc>
            <priority>
                <xsl:choose>
                    <xsl:when test="parent::menu">0.8</xsl:when>
                    <xsl:when test="parent::item/parent::menu">0.7</xsl:when>
                    <xsl:otherwise>0.6</xsl:otherwise>
                </xsl:choose>
            </priority>
            <changefreq>weekly</changefreq>
        </url>
    </xsl:template>

</xsl:stylesheet>